### ISSUE TITLE
Thoughts on converting from JS obj to actual CSS syntax?

### ISSUE THREAD

**Issue by corysimmons** [vitalets/react-native-extended-stylesheet#78]
```js
foo: {
  backgroundColor: 'red',
  padding: 10
}
```
becomes
```css
.foo {
  background-color: red;
  padding: 10;
}
```

Not important. Just a stylistic tweak.
